---
version: "3.8"
services:
  movies1:
    image: rajaram890/paymovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: rajaram890/paytrain:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  dth:
    image: rajaram890/paydth:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: rajaram890/payrecharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
